# Base image
FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Install build essentials, Python, and make
RUN apt-get update && \
    apt-get install -y build-essential python3 && \
    apt-get clean


# Install necessary libraries for Puppeteer and Chromium
RUN apt-get install -y \
    libnss3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libxrandr2 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libpci3 \
    libgconf-2-4 \
    libasound2 \
    libpangocairo-1.0-0 \
    libgtk-3-0 \
    fonts-liberation \
    libappindicator3-1 \
    libx11-xcb1 \
    && apt-get clean

# Install Chromium
RUN apt-get install -y chromium

# Install node-gyp globally
RUN npm install -g node-gyp

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

ARG NODE_ENV
ARG PORT
ARG LIVE_DB_TYPE
ARG LIVE_DB_HOST
ARG LIVE_DB_PORT
ARG LIVE_DB_USER
ARG LIVE_DB_NAME
ARG LIVE_DB_PASSWORD
ARG JWT_SECRET
ARG REFRESH_JWT_SECRET
ARG JWT_AUTH_TOKEN_EXPIRATION
ARG JWT_REFRESH_TOKEN_EXPIRATION
ARG LIVE_EMAIL_HOST
ARG LIVE_EMAIL_USER
ARG LIVE_EMAIL_PASS
ARG LIVE_EMAIL_PORT
ARG REQUEST_RATE_TTL
ARG REQUEST_RATE_LIMIT
ARG REDIS_HOST
ARG REDIS_PORT
ARG AZURE_BLOB_STORAGE_CONNECTION_STRING
ARG AZURE_BLOB_STORAGE_CONTAINER_NAME
ARG AZURE_BLOB_STORAGE_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG AUTH_V1_SERVICE_URL
ARG ORG_V1_SERVICE_URL
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG STRIPE_REDIRECT_URI
ARG STRIPE_PRO_PRICE_ID
ARG STRIPE_PREMIUM_PRICE_ID
ARG STRIPE_SUBSCRIPTION_SUCCESS_URI
ARG STRIPE_SUBSCRIPTION_CANCEL_URI
ARG FRONTEND_URL
ARG FORM_URL
ARG IP_INFO_TOKEN
ARG STRIPE_CHECKOUT_SESSION_SUCCESS_URL
ARG STRIPE_CHECKOUT_SESSION_CANCEL_URL
ARG STRIPE_CHECKOUT_SESSION_CURRENCY
ARG TICKET_PERCENTAGE_CUT
ARG STRIPE_FEE


# Set environment variables
ENV NODE_ENV=${NODE_ENV} \
    PORT=${PORT} \
    LIVE_DB_TYPE=${LIVE_DB_TYPE} \
    LIVE_DB_HOST=${LIVE_DB_HOST} \
    LIVE_DB_PORT=${LIVE_DB_PORT} \
    LIVE_DB_USER=${LIVE_DB_USER} \
    LIVE_DB_NAME=${LIVE_DB_NAME} \
    LIVE_DB_PASSWORD=${LIVE_DB_PASSWORD} \
    JWT_SECRET=${JWT_SECRET} \
    REFRESH_JWT_SECRET=${REFRESH_JWT_SECRET} \
    JWT_AUTH_TOKEN_EXPIRATION=${JWT_AUTH_TOKEN_EXPIRATION} \
    JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION} \
    LIVE_EMAIL_HOST=${LIVE_EMAIL_HOST} \
    LIVE_EMAIL_USER=${LIVE_EMAIL_USER} \
    LIVE_EMAIL_PASS=${LIVE_EMAIL_PASS} \
    LIVE_EMAIL_PORT=${LIVE_EMAIL_PORT} \
    REQUEST_RATE_TTL=${REQUEST_RATE_TTL} \
    REQUEST_RATE_LIMIT=${REQUEST_RATE_LIMIT} \
    REDIS_HOST=${REDIS_HOST} \
    REDIS_PORT=${REDIS_PORT} \
    AZURE_BLOB_STORAGE_CONNECTION_STRING=${AZURE_BLOB_STORAGE_CONNECTION_STRING} \
    AZURE_BLOB_STORAGE_CONTAINER_NAME=${AZURE_BLOB_STORAGE_CONTAINER_NAME} \
    AZURE_BLOB_STORAGE_URL=${AZURE_BLOB_STORAGE_URL} \
    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
    GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
    AUTH_V1_SERVICE_URL=${AUTH_V1_SERVICE_URL} \
    ORG_V1_SERVICE_URL=${ORG_V1_SERVICE_URL} \
    STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY} \
    STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET} \
    STRIPE_REDIRECT_URI=${STRIPE_REDIRECT_URI} \
    STRIPE_PRO_PRICE_ID=${STRIPE_PRO_PRICE_ID} \
    STRIPE_PREMIUM_PRICE_ID=${STRIPE_PREMIUM_PRICE_ID} \
    STRIPE_SUBSCRIPTION_SUCCESS_URI=${STRIPE_SUBSCRIPTION_SUCCESS_URI} \
    STRIPE_SUBSCRIPTION_CANCEL_URI=${STRIPE_SUBSCRIPTION_CANCEL_URI} \
    FRONTEND_URL=${FRONTEND_URL} \
    FORM_URL=${FORM_URL} \
    IP_INFO_TOKEN=${IP_INFO_TOKEN} \
    STRIPE_CHECKOUT_SESSION_SUCCESS_URL=${STRIPE_CHECKOUT_SESSION_SUCCESS_URL} \
    STRIPE_CHECKOUT_SESSION_CANCEL_URL=${STRIPE_CHECKOUT_SESSION_CANCEL_URL} \
    STRIPE_CHECKOUT_SESSION_CURRENCY=${STRIPE_CHECKOUT_SESSION_CURRENCY} \
    TICKET_PERCENTAGE_CUT=${TICKET_PERCENTAGE_CUT} \
    STRIPE_FEE=${STRIPE_FEE}

# Install Nest CLI globally
RUN npm install -g @nestjs/cli@latest

# Build the application
RUN npm run build

# Expose the application port
EXPOSE 5001

# Start the server using the production build with necessary Puppeteer flags
CMD ["npm", "run", "start:prod"]