import { registerAs } from '@nestjs/config';

export default registerAs('config', () => ({
  port: parseInt(process.env.PORT, 10) || 5000,
  nodenv: process.env.NODE_ENV,
}));

export const events = {
  USER_CREATED: 'USER_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  VERIFICATION_TOKEN_REQUEST: 'VERIFICATION_TOKEN_REQUEST',
  ACCOUNT_VERIFIED: 'ACCOUNT_VERIFIED',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  EMAIL_CHANGED: 'EMAIL_CHANGED',

  USER_EMAIL_CREATED: 'USER_EMAIL_CREATED',
  USER_PROFILE_CREATED: 'USER_PROFILE_CREATED',
  USER_EMAIL_VERIFIED: 'USER_EMAIL_VERIFIED',
  USER_MAGIC_SIGN_IN_LINK_CREATED: 'USER_MAGIC_SIGN_IN_LINK_CREATED',

  TEAM_CREATED: 'TEAM_CREATED',
  TEAM_INVITATION_ACCEPTED: 'TEAM_INVITATION_ACCEPTED',
  TEAM_INVITATION_DECLINED: 'TEAM_INVITATION_DECLINED',
  TEAM_MEMBER_INVITED: 'TEAM_MEMBER_INVITED',
  TEAM_MEMBER_LEFT: 'TEAM_MEMBER_LEFT',
  TEAM_MEMBER_REMOVED: 'TEAM_MEMBER_REMOVED',

  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_REASSIGNED: 'TASK_REASSIGNED',
  TASK_REMOVED: 'TASK_REMOVED',

  CHARGES_ENABLED: 'CHARGES_ENABLED',
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  INVOICE_PAYMENT_CREATED: 'INVOICE_PAYMENT_CREATED',
  INVOICE_PAYMENT_FAILED: 'INVOICE_PAYMENT_FAILED',
  INVOICE_PAYMENT_SUCCESS: 'INVOICE_PAYMENT_SUCCESS',
  STRIPE_PAYMENT_ONBOARDING_COMPLETED: 'STRIPE_PAYMENT_ONBOARDING_COMPLETED',
  PAYOUT_ENABLED: 'PAYOUT_ENABLED',
  PAYOUT_SUCCESS: 'PAYOUT_SUCCESS',
  PAYOUT_FAILED: 'PAYOUT_FAILED',

};

export const appInfo = {
  appName: 'PLAVENTI',
  appEmail: 'info@plaventi.com',
  fromEmail: 'noreply@plaventi.com',
  companyName: 'PLAVENTI',
  companyPhone: '+1 (212) 333-8888',
};

export const errors = {
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  FORBIDDEN_ERROR: 'ACCESS_DENIED_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  DATA_CONFLICT_ERROR: 'DATA_CONFLICT_ERROR',
  NOT_ACCEPTABLE_ERROR: 'NOT_ACCEPTABLE_ERROR',
  UNPROCESSABLE_DATA_ERROR: 'UNPROCESSABLE_DATA_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

export const roles = {
  ORGANIZER: 'organizer',
  ATTENDEE: 'attendee',
  ADMIN: 'admin',
};
