export const events = {
  SUPPORT_CREATED: 'SUPPORT_CREATED',
  SUPPORT_UPDATED: 'SUPPORT_UPDATED',
  SUPPORT_STATUS_CHANGED: 'SUPPORT_STATUS_CHANGED',
  SUPPORT_STATUS_CLOSED: 'SUPPORT_STATUS_CLOSED',

  USER_CREATED: 'USER_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  VERIFICATION_TOKEN_REQUEST: 'VERIFICATION_TOKEN_REQUEST',
  ACCOUNT_VERIFIED: 'ACCOUNT_VERIFIED',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  EMAIL_CHANGED: 'EMAIL_CHANGED',

  USER_EMAIL_CREATED: 'USER_EMAIL_CREATED',
  USER_PROFILE_CREATED: 'USER_PROFILE_CREATED',
  USER_EMAIL_VERIFIED: 'USER_EMAIL_VERIFIED',
  USER_MAGIC_SIGN_IN_LINK_CREATED: 'USER_MAGIC_SIGN_IN_LINK_CREATED',
};

export const appInfo = {
  appName: 'PLAVENTI',
  appEmail: 'info@plaventi.com',
  fromEmail: 'noreply@plaventi.com',
  companyName: 'PLAVENTI',
  companyPhone: '+1 (212) 333-8888',
};

export const errors = {
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  FORBIDDEN_ERROR: 'ACCESS_DENIED_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  DATA_CONFLICT_ERROR: 'DATA_CONFLICT_ERROR',
  NOT_ACCEPTABLE_ERROR: 'NOT_ACCEPTABLE_ERROR',
  UNPROCESSABLE_DATA_ERROR: 'UNPROCESSABLE_DATA_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

export const roles = {
  ADMIN: 'ADMIN',
  REGULAR: 'REGULAR',
};
